### ISSUE TITLE
🗺 v1.0 RoadMap / TodoList 

### ISSUE THREAD

**Issue by arvinxx** [ant-design/html2sketch#22]
### TodoList

- [ ]  针对 Symbol 的布局智能识别与解析（留到 1.x 中）
- [x] css 中 transform 的解析 #12  #30 
- [x] 带 g、rect、ellipse、text、ref 等非 path 路径的 Svg 解析（ #10  相关PR #20 #19   已初步实现 90% ，待用例覆盖）
- [x] li 类型的节点解析

### 已知 Bug

- [x] 部分未覆盖到的文本坐标位置，有待提 issue 来覆盖解决 #32 #39 
- [x] 某些 canvas 无法 toDataUrl ，报错 `Tainted canvases may not be exported.` （存在图片跨域问题，如果没法拿到 image 的 src 就无解） https://github.com/ant-design/html2sketch/pull/35/commits/07375cee7a0dd40a2416965e74fd7a795f70f0cb
- [x] 伪类的绝对定位解析 #29  
- [x] 多行文本行高问题 #24 
- [x] 图片 URL 不是 http 开头时会解析报错 #23 
- [x] background 为 svg 时可能会是空白的。 #18 
- [x] 文本存在不透明度时没有解析出来 #25
